### ISSUE TITLE
Latex style error when plt.show() or fig.savefig()

### ISSUE THREAD

**Issue by BoZeng1997** [lyyc199586/cm-vis#1]
# Description

Error when trying to show plots by `plt.show()` or save figs by `fig.savefig('a.png')` by running script (copied from [pf_scheme.ipynb](https://github.com/lyyc199586/cm-vis/blob/main/examples/pf_scheme.ipynb) section either discrete crack or phase-field crack). No figure shown or saved. 

The script works when this line is commented out
```
plt.style.use('fem')
```

# Steps to reproduce

```
conda deactivate # back to base env
pip install git+https://github.com/lyyc199586/cm-vis.git
```
then generate a script `pf_scheme.py` with content copied from [pf_scheme.ipynb](https://github.com/lyyc199586/cm-vis/blob/main/examples/pf_scheme.ipynb) section either discrete crack or phase-field crack. Add  `plt.show()` or `fig.savefig('a.png')` to the end of the script.
```
python3 pf_scheme.py
```
should see the error msg.

# Error msg

```
Traceback (most recent call last):
  File "/home/bz75/projects/yuan/pf_scheme.py", line 56, in <module>
    fig.savefig("pff_illu_c.png")
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/text.py", line 748, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/text.py", line 373, in _get_layout
    _, lp_h, lp_d = _get_text_metrics_with_cache(
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/text.py", line 69, in _get_text_metrics_with_cache
    return _get_text_metrics_with_cache_impl(
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/text.py", line 77, in _get_text_metrics_with_cache_impl
    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 213, in get_text_width_height_descent
    return super().get_text_width_height_descent(s, prop, ismath)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 652, in get_text_width_height_descent
    return self.get_texmanager().get_text_width_height_descent(
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/texmanager.py", line 363, in get_text_width_height_descent
    dvifile = cls.make_dvi(tex, fontsize)
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/texmanager.py", line 295, in make_dvi
    cls._run_checked_subprocess(
  File "/home/bz75/mambaforge3/lib/python3.10/site-packages/matplotlib/texmanager.py", line 258, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error --output-directory=tmp8n2znxi3 4a20e6ffd5ab334c50be8c6aebc1188a.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./4a20e6ffd5ab334c50be8c6aebc1188a.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))

! LaTeX Error: File `type1cm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7 \usepackage
               {type1ec}^^M
No pages of output.
Transcript written on tmp8n2znxi3/4a20e6ffd5ab334c50be8c6aebc1188a.log.
```
# conda info

```
     active environment : base
    active env location : /home/bz75/mambaforge3
            shell level : 1
       user config file : /home/bz75/.condarc
 populated config files : /home/bz75/mambaforge3/.condarc
                          /home/bz75/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /home/bz75/mambaforge3  (writable)
      conda av data dir : /home/bz75/mambaforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.software.inl.gov/public/linux-64
                          https://conda.software.inl.gov/public/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/bz75/mambaforge3/pkgs
                          /home/bz75/.conda/pkgs
       envs directories : /home/bz75/mambaforge3/envs
                          /home/bz75/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.5.0-21-generic ubuntu/22.04.4 glibc/2.35
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by lyyc199586** [comment]
That's an old error for rendering TeX in matplotlib on Ubuntu, try install `type1cm.sty` with:
```
sudo apt install texlive-latex-extra cm-super dvipng
```

For your ref:
https://stackoverflow.com/questions/11354149/python-unable-to-render-tex-in-matplotlib

https://blog.csdn.net/weixin_46584887/article/details/125726135

**Comment by BoZeng1997** [comment]
issue solved
